project:
  output-dir: docs
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: about
      - href: blog.qmd  
        text: blog
#      - href: teg_cv.pdf
#        text: Short CV 
#    right:
#    - icon: envelope
#      href: mailto:tegedik@gmail.com
#    - icon: github
#      href: https://github.com/tegedik
#    - icon: box
#      href: https://bsky.app/profile/tegedik.bsky.social
#    - icon: mastodon
#      href: https://fosstodon.org/@thrnsgdk
#    - icon: twitter
#      href: https://twitter.com/tahirenesgedik
#    - icon: linkedin
#      href: https://www.linkedin.com/in/tegedik/
#  page-footer:
#    background: light # or dark
#    center:
#      - "Copyright 2023, Tahir Enes Gedik"
  site-url: https://tegedik.github.io
  open-graph: true
  twitter-card:
    creator: "@tahirenesgedik"
format:
  html:
    theme: 
      - simplex
    css: styles.css
    toc: true



